// Ordförståelsetest åk 4–5: 100 ord
window.__ordtestWords = [
  {"word":"rolig","options":["skämmig","sorglig","tråkig","skojig"],"answer":3},
  {"word":"alternativ","options":["storhet","svaghet","möjlighet","svårighet"],"answer":2},
  {"word":"bedöma","options":["falsifiera","betygsätta","korrigera","fallera"],"answer":1},
  {"word":"anonym","options":["känd","ökänd","okänd","berömd"],"answer":2},
  {"word":"oavsett","options":["därför","trots allt","följdaktligen","följaktligen"],"answer":1},
  {"word":"korrekt","options":["rätt","lagom","minimal","ungefärlig"],"answer":0},
  {"word":"formulera","options":["experimentera","uttrycka sig","diskutera","traversera"],"answer":1},
  {"word":"tillräcklig","options":["utmärkt","svårsmält","lång","acceptabel"],"answer":3},
  {"word":"befolkning","options":["folkgrupp","invandrare","invånare","utflyttning"],"answer":2},
  {"word":"erövra","options":["koalition","utbyta","inta","samarbeta"],"answer":2},
  {"word":"import","options":["smuggling","komfort","transport","utrikeshandel"],"answer":3},
  {"word":"symbol","options":["tecken","trumma","stjärnbild","sfär"],"answer":0},
  {"word":"skörda","options":["lagra","samla in","sprida ut","plantera"],"answer":1},
  {"word":"frätande","options":["upplösande","upptagen","uppbyggande","uppförande"],"answer":0},
  {"word":"sällsynt","options":["mänsklig","folklig","synfel","ovanlig"],"answer":3},
  {"word":"skala","options":["utredning","inventering","utvinning","storleksförhållande"],"answer":3},
  {"word":"rymma","options":["förvaring","innehålla","instängd","frysa"],"answer":1},
  {"word":"medelvärde","options":["genomsnitt","utsnitt","genomskärning","måttband"],"answer":0},
  {"word":"area","options":["längdenhet","omkrets","yta","material"],"answer":2},
  {"word":"sorgsen","options":["förstenad","sorterad","försenad","ledsen"],"answer":3},
  {"word":"vätska","options":["flytande","fast","plasma","gas"],"answer":0},
  {"word":"orsak","options":["belöning","anledning","avslutning","följd"],"answer":1},
  {"word":"konsekvens","options":["följd","början","orsak","metod"],"answer":0},
  {"word":"förändring","options":["likhet","skillnad","vanlighet","ordning"],"answer":1},
  {"word":"jämföra","options":["granska","jämnställa","undersöka","sammanfoga"],"answer":2},
  {"word":"observera","options":["iaktta","gissa","glömma","undvika"],"answer":0},
  {"word":"undersöka","options":["utforska","avsluta","hoppa över","låtsas"],"answer":0},
  {"word":"resonera","options":["tänka högt","räkna ut","gissa vilt","samla ihop"],"answer":0},
  {"word":"sammanfatta","options":["förkorta","ändra","översätta","utveckla"],"answer":0},
  {"word":"beskriva","options":["avgöra","återge","samla","ändra"],"answer":1},
  {"word":"förklara","options":["tydliggöra","försvåra","förminska","rätta"],"answer":0},
  {"word":"påstå","options":["mena","bevisa","tvivla","fråga"],"answer":0},
  {"word":"bevisa","options":["styrka","gissa","förneka","påstå"],"answer":0},
  {"word":"påverka","options":["inverka","kopiera","samla","lämna"],"answer":0},
  {"word":"utveckla","options":["förstöra","förbättra","förkorta","sudda ut"],"answer":1},
  {"word":"minska","options":["öka","avta","växa","skapa"],"answer":1},
  {"word":"öka","options":["avta","växa","sjunka","försvinna"],"answer":1},
  {"word":"förbättra","options":["försämra","utveckla","förminska","dölja"],"answer":1},
  {"word":"försämra","options":["förbättra","förvärra","förstora","förtydliga"],"answer":1},
  {"word":"bevara","options":["slänga","spara","förändra","förstöra"],"answer":1},
  {"word":"förstöra","options":["bygga upp","skada svårt","förklara","utvidga"],"answer":1},
  {"word":"noggrant","options":["slarvigt","ordentligt","oroligt","hastigt"],"answer":1},
  {"word":"tillfällig","options":["kortvarig","hemlig","viktig","ständig"],"answer":0},
  {"word":"ständig","options":["ovanlig","varaktig","kort","ensam"],"answer":1},
  {"word":"vanlig","options":["sällsynt","ofta förekommande","dyr","gammaldags"],"answer":1},
  {"word":"ovanlig","options":["sällsynt","tydlig","snabb","ordnad"],"answer":0},
  {"word":"särskild","options":["vanlig","speciell","hemlig","kort"],"answer":1},
  {"word":"viktig","options":["betydelsefull","billig","försenad","okänd"],"answer":0},
  {"word":"betydelsefull","options":["onödig","viktig","hastig","säker"],"answer":1},
  {"word":"möjlig","options":["omöjlig","genomförbar","förbjuden","försenad"],"answer":1},
  {"word":"omöjlig","options":["enkel","ogenomförbar","möjlig","nästan klar"],"answer":1},
  {"word":"lösning","options":["svar","fråga","orsak","misstag"],"answer":0},
  {"word":"problem","options":["svårighet","lösning","fördel","vinst"],"answer":0},
  {"word":"metod","options":["arbetssätt","slump","resultat","fråga"],"answer":0},
  {"word":"strategi","options":["plan","misstag","regelbrott","gissning"],"answer":0},
  {"word":"resultat","options":["orsak","utfall","början","jämförelse"],"answer":1},
  {"word":"slutsats","options":["avgörande","slutpunkt","slutomdöme","inledning"],"answer":2},
  {"word":"exempel","options":["förebild","illustration","regel","problem"],"answer":1},
  {"word":"bevis","options":["önskan","stöd","gissning","invändning"],"answer":1},
  {"word":"fördel","options":["plus","minus","hinder","misstag"],"answer":0},
  {"word":"nackdel","options":["plus","minus","möjlighet","belöning"],"answer":1},
  {"word":"tolka","options":["förstå","rita av","samla","gömma"],"answer":0},
  {"word":"uttryck","options":["fras","regelbrott","redskap","slutsvar"],"answer":0},
  {"word":"innehåll","options":["insida","utsida","färg","storlek"],"answer":0},
  {"word":"huvudidé","options":["kärna","första ordet","svår mening","rubrik"],"answer":0},
  {"word":"budskap","options":["mening","räknesätt","stavregel","bildtext"],"answer":0},
  {"word":"tema","options":["ämne","författare","ordantal","slutmening"],"answer":0},
  {"word":"detalj","options":["smådel","helhet","slump","sammanfattning"],"answer":0},
  {"word":"helhet","options":["alltihop","minsta delen","exempel","orsak"],"answer":0},
  {"word":"rubrik","options":["titel","stycke","bild","åsikt"],"answer":0},
  {"word":"sammanhang","options":["kontext","felskrivning","ensamhet","svarsalternativ"],"answer":0},
  {"word":"invånare","options":["boende","turist","elev","ledare"],"answer":0},
  {"word":"samhälle","options":["gemenskap","byggnad","skolgård","fritid"],"answer":0},
  {"word":"yrke","options":["arbete","boplats","skolämne","släktnamn"],"answer":0},
  {"word":"tradition","options":["vana","oväder","karta","argument"],"answer":0},
  {"word":"kultur","options":["levnadssätt","hus","musik","lagförslag"],"answer":0},
  {"word":"historia","options":["dåtid","framtid","gissning","regel"],"answer":0},
  {"word":"framtid","options":["senare tid","dåtid","gammalt","glömska"],"answer":0},
  {"word":"nutid","options":["nuvarande tid","forntid","framtid","nästa vecka"],"answer":0},
  {"word":"miljö","options":["omgivning","skog","vatten","uppgift"],"answer":0},
  {"word":"resurs","options":["tillgång","hinder","fara","misslyckande"],"answer":0},
  {"word":"energi","options":["drivkraft","byggnad","färg","prov"],"answer":0},
  {"word":"material","options":["ämne","räknesätt","känsla","plats"],"answer":0},
  {"word":"egenskap","options":["kännetecken","föremål","händelse","tidpunkt"],"answer":0},
  {"word":"fast","options":["flytande","hård","gasformig","upplöst"],"answer":1},
  {"word":"gas","options":["luftämne","metall","vätska","jordlager"],"answer":0},
  {"word":"temperatur","options":["värmegrad","längd","vikt","hastighet"],"answer":0},
  {"word":"mätning","options":["uppmätning","chansning","glömska","målning"],"answer":0},
  {"word":"enhet","options":["måttslag","problem","slutsats","berättelse"],"answer":0},
  {"word":"volym","options":["rymd","vikt","längd","värme"],"answer":0},
  {"word":"omkrets","options":["ytterlinje","yta","höjd","färg"],"answer":0}
];
